### ISSUE TITLE
Clustal validation error

### ISSUE THREAD

**Issue by MatthewRalston** [zy4/reformat.js#1]
In the first for loop, you check if the number of 'elements' per line of the alignment is equal to 3 and equal to 2.
https://github.com/zy4/reformat.js/blob/master/src/reformat.js#L293
This can never be true. Either the name and sequence is present, or the name, sequence, and length is present but these are mutually exclusive cases.

**Comment by zy4** [comment]
Thanks! I fixed it already and will publish it within the next days.

**Comment by MatthewRalston** [comment]
@zy4 this same line also happens to evaluate the clustal conservation line ("*:." characters). In this case, there is only 1 non-whitespace string of characters. Have you tested this? I would like to see the output. I have modified your code for my own uses, and I'd like to see if you can reproduce some of the same errors. The only function I have trouble with is validateClustal.

**Comment by zy4** [comment]
This should not work by now. The conservation validation is only implemented in an abstract sense and should be completed in the future. We are really open for pull requests by the way!
